FROM alpine:3.20

RUN apk add --no-cache \
    restic \
    git \
    bash \
    curl \
    sed \
    ca-certificates

COPY create_template_gcs.sh /usr/local/bin/create_template_gcs.sh
RUN chmod +x /usr/local/bin/create_template_gcs.sh

ENTRYPOINT ["bash", "/usr/local/bin/create_template_gcs.sh"]
